[params.plausible]
   enable = true
   domain = "my-plausible-domain-id-dashboard"
   custom_js_domain = ""
   selfhosted_domain = ""
   public_dashboard = false
   outbound_link = false
   debug = false  # debug mode
   # For embeded dashboard
   dash_disable = false
   dash_link = "https://plausible.io/share/yourdomain?auth=AZE1234RTYUOP67"
   dash_theme = ""
   dash_bgcolor = ""
[params.plausible_version]
   id = "1.9.1"
